/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/shop'
    | '/product/$slug'
    | '/api/public/media/$'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/shop'
    | '/product/$slug'
    | '/api/public/media/$'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/shop'
    | '/product/$slug'
    | '/api/public/media/$'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopRoute: typeof ShopRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ShopRoute: ShopRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
